export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Bagrat J-e",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpg",
    username: "Data",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpg",
    username: "Levan from the sky",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpg",
    username: "Elene Jincharadze",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpg",
    username: "Nini Papaliashvili",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpg",
    username: "Giorgi Maglakelidze",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpg",
    username: "Giorgi Cnobila",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpg",
    username: "Kate Gordadze",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpg",
    username: "Davit Khimsho Khimshiashvili",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpg",
    username: "Piro Paruli Konverti",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "სჯობს სიცოცხლესა ნაძრახსა სიკვდილი სახელოვანი და კიდევ Love Is Love",
    photo: "assets/person/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "ხვალ 20:00 საათზე მეტალიკას კონცერტზე ვუკრავ და მოდით ჩემი ხათრით <3",
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 42,
    comment: 1,
  },
  {
    id: 3,
    desc: "ჩამოვარდი ხიდან -- ლევანა ვარ ციდან. haralali haralalo",
    photo: "assets/post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "კარბონარა კობრა კობრათი, მე გავაკეთე golden ხელები მაქვს",
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 73,
    comment: 3,
  },
  {
    id: 5,
    desc: "2pac რა გინდა? GTXOV SHEMESHVIIIIII",
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 0,
    comment: 5,
  },
  {
    id: 6,
    desc: "Omg dude barely chavxure this fucking game",
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 43,
    comment: 6,
  },
  {
    id: 7,
    desc: "New Car magrad driftaobs ra",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "busastvis vedzebt sacoles umjobesia icodes saxlis dalageba da 2 hqondes 2 diplomi, dedamtili k.gordadze",
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "!",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 111,
    comment: 2,
  },
  {
    id: 10,
    desc: "კუკურის გაზაფხული-ზაფხულის ფოტოსესია (თამამი ფოტოები)",
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 1043,
    comment: 12,
  },
];
